# Site settings
title: Zachary Choffin
email: zmchoffin@crimson.ua.edu
description: Academic webpage of Zachary Choffin
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
collections:
  projects:
    output: true
    permalink: /projects/:path/

affiliation: >
    Zachary Choffin<br/>
    Ph.D. Candidate in Electrical Engineering<br/>
    The University of Alabama

location: >
  The University of Alabama<br/>
  245 7th Ave Suite 2004<br/>
  Tuscaloosa, AL 35401

contact: >
    <a href="mailto:zmchoffin@crimson.ua.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Zachary via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
  - name: research
#  - name: software
#  - name: team
  - name: projects
    dropdown: true
    items:
      - name: OSRS_AI
        url: /projects/osrs_AI
#      - name: example_2
#        url: /projects/example_2

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
